doctrine:
    dbal:
        driver: pdo_sqlite
        url: '%env(resolve:DATABASE_URL)%'
        override_url: true
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
        dql:
            string_functions:
                IF: DoctrineExtensions\Query\Sqlite\IfElse
                IFNULL: DoctrineExtensions\Query\Sqlite\IfNull
                DATE: DoctrineExtensions\Query\Sqlite\Date
