security:
  providers:
    from_database:
      entity:
        class: App\Entity\Competiteur
        property: username

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      pattern: ^/
      user_checker: App\Checker\UserChecker
      anonymous: true
      form_login:
        login_path: login
        check_path: login
        default_target_path: /
      logout:
        path: /logout
        target: /login
      remember_me:
        secret: '%kernel.secret%'

  role_hierarchy:
    ROLE_ENTRAINEUR: ROLE_LOISIR
    ROLE_COMPETITEUR: ROLE_LOISIR
    ROLE_CAPITAINE: ROLE_COMPETITEUR
    ROLE_ADMIN: ROLE_CAPITAINE

  access_control:
    - { path: ^/compte, roles: ROLE_LOISIR }
    - { path: ^/backoffice/update, roles: [ ROLE_ADMIN ] }
    - { path: ^/backoffice/championnat/new, roles: [ ROLE_ADMIN ] }
    - { path: ^/backoffice/championnat/edit, roles: [ ROLE_ADMIN ] }
    - { path: ^/backoffice/championnat/delete, roles: [ ROLE_ADMIN ] }
    - { path: ^/backoffice/division/delete, roles: [ ROLE_ADMIN ] }
    - { path: ^/backoffice/division/edit, roles: [ ROLE_ADMIN ] }
    - { path: ^/backoffice/division/new, roles: [ ROLE_ADMIN ] }
    - { path: ^/backoffice/equipe/delete, roles: [ ROLE_ADMIN ] }
    - { path: ^/backoffice/equipe/new, roles: [ ROLE_ADMIN ] }
    - { path: ^/backoffice/competiteur/edit, roles: [ ROLE_ADMIN ] }
    - { path: ^/backoffice/competiteur/new, roles: [ ROLE_ADMIN ] }
    - { path: ^/backoffice/competiteur/renouveler/certificat, roles: [ ROLE_ADMIN ] }
    - { path: ^/backoffice/competiteur/resend-welcome-mail, roles: [ ROLE_ADMIN ] }
    - { path: ^/backoffice/competiteur/delete, roles: [ ROLE_ADMIN ] }
    - { path: ^/backoffice/competiteur/password/update, roles: [ ROLE_ADMIN ] }
    - { path: ^/backoffice/competiteurs/mail/edit, roles: [ ROLE_ADMIN ] }
    - { path: ^/backoffice/competiteurs/mail/certif-medic-perim, roles: [ ROLE_ADMIN ] }
    - { path: ^/backoffice/competiteurs/import-file, roles: [ ROLE_ADMIN ] }
    - { path: ^/backoffice/competiteurs/import-file/save, roles: [ ROLE_ADMIN ] }
    - { path: ^/backoffice/competiteurs/import-file/read, roles: [ ROLE_ADMIN ] }
    - { path: ^/backoffice, roles: [ ROLE_CAPITAINE, ROLE_ADMIN ] }
    - { path: ^/journee/edit, roles: [ ROLE_CAPITAINE, ROLE_ADMIN ] }
    - { path: ^/journee/empty, roles: [ ROLE_CAPITAINE, ROLE_ADMIN ] }
    - { path: ^/journee, roles: ROLE_LOISIR }
    - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/aide, roles: ROLE_LOISIR }
    - { path: ^/contacter, roles: ROLE_LOISIR }
    - { path: ^/informations, roles: ROLE_LOISIR }
    - { path: ^/tournois, roles: ROLE_LOISIR }
    - { path: ^/liste/tournois, roles: ROLE_LOISIR }
    - { path: ^/liste/tableaux/tournois, roles: ROLE_LOISIR }

  encoders:
    App\Entity\Competiteur:
      algorithm: bcrypt
      cost: 12