security:
    providers:
        from_database:
            entity:
                class: App\Entity\Competiteur
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            anonymous: true
            form_login:
                login_path: login
                check_path: login
                default_target_path: /
            logout:
                path: /logout
                target: /login
            remember_me:
                secret: '%kernel.secret%'

    role_hierarchy:
        ROLE_JOUEUR: ROLE_VISITEUR
        ROLE_CAPITAINE: [ROLE_JOUEUR, ROLE_VISITEUR]
        ROLE_ADMIN: [ROLE_CAPITAINE, ROLE_JOUEUR, ROLE_VISITEUR]

    access_control:
        - { path: ^/journee/edit, roles: ROLE_CAPITAINE }
        - { path: ^/compte, roles: ROLE_JOUEUR }
        - { path: ^/backoffice, roles: ROLE_CAPITAINE }
        - { path: ^/journee/(departementale|paris|disponibilite), roles: ROLE_VISITEUR }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }

    encoders:
        App\Entity\Competiteur:
            algorithm: bcrypt
            cost: 12