security:
    providers:
        from_database:
            entity:
                class: App\Entity\Competiteur
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            anonymous: true
            form_login:
                login_path: login
                check_path: login
                default_target_path: /
            logout:
                path: /logout
                target: /login
            remember_me:
                secret: '%kernel.secret%'

    role_hierarchy:
        ROLE_JOUEUR: ROLE_LOISIR
        ROLE_CAPITAINE: ROLE_JOUEUR
        ROLE_ADMIN: ROLE_CAPITAINE

    access_control:
        - { path: ^/composition, roles: ROLE_CAPITAINE }
        - { path: ^/compte, roles: ROLE_LOISIR }
        - { path: ^/backoffice, roles: ROLE_CAPITAINE }
        - { path: ^/journee, roles: ROLE_LOISIR }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/contact, roles: ROLE_LOISIR }
        - { path: ^/informations, roles: ROLE_CAPITAINE }

    encoders:
        App\Entity\Competiteur:
            algorithm: bcrypt
            cost: 12