security:
    providers:
        from_database:
            entity:
                class: App\Entity\Competiteur
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            form_login:
                login_path: login
                check_path: login
                default_target_path: /journee/1
            logout:
                path: /logout
                target: /journee/1

    access_control:
        - { path: ^/journee/edit, roles: ROLE_CAPITAINE }
        - { path: ^/compte, roles: ROLE_JOUEUR }

    encoders:
        App\Entity\Competiteur:
            algorithm: bcrypt
            cost: 12