security:
  providers:
    from_database:
      entity:
        class: App\Entity\Competiteur
        property: username

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      pattern: ^/
      user_checker: App\Checker\UserChecker
      anonymous: true
      form_login:
        login_path: login
        check_path: login
        default_target_path: /
      logout:
        path: /logout
        target: /login
      remember_me:
        secret: '%kernel.secret%'

  role_hierarchy:
    ROLE_ENTRAINEUR: ROLE_LOISIR
    ROLE_COMPETITEUR: ROLE_LOISIR
    ROLE_CAPITAINE: ROLE_COMPETITEUR
    ROLE_ADMIN: ROLE_CAPITAINE

  access_control:
    - { path: ^/compte, roles: ROLE_LOISIR }
    - { path: ^/backoffice/championnat/, roles: [ ROLE_ADMIN ] }
    - { path: ^/backoffice/division/, roles: [ ROLE_ADMIN ] }
    - { path: ^/backoffice/equipe/edit/, roles: [ ROLE_CAPITAINE, ROLE_ADMIN ] }
    - { path: ^/backoffice/equipe/, roles: [ ROLE_ADMIN ] }
    - { path: ^/backoffice/competiteur/export-excel, roles: [ ROLE_CAPITAINE, ROLE_ADMIN ] }
    - { path: ^/backoffice/competiteur/, roles: [ ROLE_ADMIN ] }
    - { path: ^/backoffice/settings, roles: [ ROLE_ADMIN ] }
    - { path: ^/backoffice, roles: [ ROLE_CAPITAINE, ROLE_ADMIN ] }
    - { path: ^/journee/edit, roles: [ ROLE_CAPITAINE, ROLE_ADMIN ] }
    - { path: ^/journee/empty, roles: [ ROLE_CAPITAINE, ROLE_ADMIN ] }
    - { path: ^/journee, roles: ROLE_LOISIR }
    - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/aide, roles: IS_AUTHENTICATED_REMEMBERED }
    - { path: ^/contacter, roles: IS_AUTHENTICATED_REMEMBERED }
    - { path: ^/informations, roles: IS_AUTHENTICATED_REMEMBERED }
    - { path: ^/tournois, roles: IS_AUTHENTICATED_REMEMBERED }

  encoders:
    App\Entity\Competiteur:
      algorithm: bcrypt
      cost: 12