twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
      nb_joueurs_compo_dep: "%nb_joueurs_compo_dep%"
      nb_joueurs_compo_paris_haut: "%nb_joueurs_compo_paris_haut%"
      nb_joueurs_compo_paris_bas: "%nb_joueurs_compo_paris_bas%"
      limite_brulage_dep: "%limite_brulage_dep%"
      limite_brulage_paris: "%limite_brulage_paris%"
      limite_pre_brulage_dep: "%limite_pre_brulage_dep%"
      limite_pre_brulage_paris: "%limite_pre_brulage_paris%"