twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
      limite_brulage_dep: "%limite_brulage_dep%"
      limite_brulage_paris: "%limite_brulage_paris%"
      limite_pre_brulage_dep: "%limite_pre_brulage_dep%"
      limite_pre_brulage_paris: "%limite_pre_brulage_paris%"