vich_uploader:
    db_driver: orm

    mappings:
        property_image:
            uri_prefix: /images/profile_pictures
            upload_destination: '%kernel.project_dir%/public/images/profile_pictures'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            delete_on_remove: true