parameters:
  fftt_api_login: '%env(FFTT_API_LOGIN)%'
  fftt_api_password: '%env(FFTT_API_PASSWORD)%'
  encryption_iv: '%env(ENCRYPTION_IV)%'
  decryption_key: '%env(DECRYPTION_KEY)%'
  default_password: '%env(DEFAULT_PASSWORD)%'
  maintenance_file_path: '%kernel.project_dir%/public/.maintenance'
  club_id: '%env(CLUB_ID)%'
  club_name: '%env(CLUB_NAME)%'
  time_limit_ajax: '%env(TIME_LIMIT_AJAX)%'
  nb_joueurs_default_division: '%env(NB_JOUEURS_DEFAULT_DIVISION)%'
  read_md_path: '%env(READ_MD_PATH)%'
  template_import_path: '%env(TEMPLATE_IMPORT_PATH)%'
  departements_path: '%env(DEPARTEMENTS_PATH)%'
  default_nb_points: '%env(DEFAULT_NB_POINTS)%'
  club_diminutif: '%env(CLUB_DIMINUTIF)%'
  club_email: '%env(CLUB_EMAIL)%'
  time_reset_password_hour: '%env(TIME_RESET_PASSWORD_HOUR)%'
  time_init_password_day: '%env(TIME_INIT_PASSWORD_DAY)%'
  url_prod: '%env(URL_PROD)%'
  url_get_tournois: '%env(URL_GET_TOURNOIS)%'
  host_get_tournois: '%env(HOST_GET_TOURNOIS)%'
  referer_get_tournois: '%env(REFERER_GET_TOURNOIS)%'
  origin_get_tournois: '%env(ORIGIN_GET_TOURNOIS)%'
  log_file_path: '%env(LOG_FILE_PATH)%'
  fichier_upload_path: '%env(FICHIER_UPLOAD_PATH)%'

services:
  _defaults:
    autowire: true
    autoconfigure: true
  App\:
    resource: '../src/*'
    exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

  App\Controller\:
    resource: '../src/Controller'
    tags: [ 'controller.service_arguments' ]

  App\EventListener\MaintenanceListener:
    arguments:
      - '%maintenance_file_path%'
      - '@twig'
    tags:
      - { name: 'kernel.event_listener', event: kernel.request }

  App\EventListener\ImageCacheSubscriber:
    tags:
      - { name: 'doctrine.event_listener', event: preUpdate }
      - { name: 'doctrine.event_listener', event: preRemove }